spring:
  data:
    mongodb:
      ## 사용할 Mongo DB에 대한 접근 정보에 대한 설정. 향후 환경변수 등으로 대체할 것.
      uri: mongodb://root:example@192.168.155.58:27017/birding-record?authSource=admin&authMechanism=SCRAM-SHA-1
